// useWordExport.js
// Drop this file into your src/ folder
// Import in App.jsx with: import { exportToWord } from './useWordExport'

import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType, ShadingType } from "docx";
import { saveAs } from "file-saver";

const GREEN = "2C4A3E";
const GOLD = "D4A847";
const CREAM = "F7F4EF";
const WHITE = "FFFFFF";

function heading1(text) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 400, after: 200 },
    run: { color: GREEN, bold: true, size: 36 }
  });
}

function heading2(text) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 300, after: 150 },
  });
}

function body(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    spacing: { after: 120 },
  });
}

function bullet(text) {
  return new Paragraph({
    children: [new TextRun({ text: `— ${text}`, size: 22 })],
    spacing: { after: 80 },
    indent: { left: 360 },
  });
}

function divider() {
  return new Paragraph({
    text: "",
    border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" } },
    spacing: { before: 200, after: 200 },
  });
}

function labelValue(label, value) {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 22, color: GREEN }),
      new TextRun({ text: value, size: 22 }),
    ],
    spacing: { after: 100 },
  });
}

// ─── TOOL 1: STRATEGY DIAGNOSTIC ─────────────────────────────────────────────
export async function exportDiagnostic({ scores, dims, slabels, risks, cautions, strengths, roadmapActions, riskMsgs }) {
  const avg = Object.values(scores).reduce((a, b) => a + b, 0) / 6;
  const ml = avg < 2 ? "Critical" : avg < 3 ? "Weak" : avg < 4 ? "Developing" : avg < 5 ? "Capable" : "Leading";

  const rows = dims.map(dim => new TableRow({
    children: [
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: dim.label, bold: true, size: 20 })] })], width: { size: 40, type: WidthType.PERCENTAGE } }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${scores[dim.id]} — ${slabels[scores[dim.id]]}`, size: 20 })] })], width: { size: 30, type: WidthType.PERCENTAGE } }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: dim.levels[scores[dim.id]-1]?.desc || "", size: 18, color: "555555" })] })], width: { size: 30, type: WidthType.PERCENTAGE } }),
    ]
  }));

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("Strategy–Execution Diagnostic"),
        labelValue("Overall Score", `${avg.toFixed(1)} / 5.0 — ${ml}`),
        labelValue("Critical Gaps", String(risks.length)),
        labelValue("Caution Areas", String(cautions.length)),
        labelValue("Strengths", String(strengths.length)),
        divider(),
        heading2("Dimension Scores"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["Dimension", "Score", "Description"].map(h =>
                new TableCell({
                  shading: { type: ShadingType.SOLID, color: GREEN },
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })]
                })
              )
            }),
            ...rows
          ]
        }),
        ...(risks.length > 0 ? [
          divider(),
          heading2("Key Risk Areas"),
          ...risks.flatMap(dim => [
            new Paragraph({ children: [new TextRun({ text: dim.label, bold: true, size: 22, color: "B94040" })], spacing: { before: 200, after: 80 } }),
            body(riskMsgs[dim.id]),
          ])
        ] : []),
        divider(),
        heading2("Improvement Roadmap"),
        ...[
          { label: "Immediate — Address First", dims: risks },
          { label: "Short-Term — Strengthen", dims: cautions },
          { label: "Sustain — Protect Strengths", dims: strengths },
        ].filter(t => t.dims.length > 0).flatMap(tier => [
          new Paragraph({ children: [new TextRun({ text: tier.label, bold: true, size: 22, color: GREEN })], spacing: { before: 240, after: 100 } }),
          ...tier.dims.flatMap(dim => [
            new Paragraph({ children: [new TextRun({ text: dim.label, bold: true, size: 20 })], spacing: { before: 160, after: 60 } }),
            ...roadmapActions[dim.id].map(a => bullet(a))
          ])
        ]),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Strategy-Diagnostic.docx");
}

// ─── TOOL 2: INITIATIVE PRIORITISATION ───────────────────────────────────────
export async function exportPrioritisation({ initiatives, tiers }) {
  const sorted = [...initiatives].sort((a, b) => b.weightedScore - a.weightedScore);

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("Initiative Prioritisation Report"),
        labelValue("Total Initiatives", String(initiatives.length)),
        labelValue("Do Now", String(sorted.filter(i => i.weightedScore >= 3.8).length)),
        labelValue("Plan", String(sorted.filter(i => i.weightedScore >= 2.8 && i.weightedScore < 3.8).length)),
        labelValue("Defer", String(sorted.filter(i => i.weightedScore >= 2.0 && i.weightedScore < 2.8).length)),
        labelValue("Stop", String(sorted.filter(i => i.weightedScore < 2.0).length)),
        divider(),
        heading2("Priority Ranking"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["#", "Initiative", "Owner", "Score", "Tier"].map(h =>
                new TableCell({
                  shading: { type: ShadingType.SOLID, color: GREEN },
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })]
                })
              )
            }),
            ...sorted.map((init, idx) => {
              const tier = init.weightedScore >= 3.8 ? "Do Now" : init.weightedScore >= 2.8 ? "Plan" : init.weightedScore >= 2.0 ? "Defer" : "Stop";
              return new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(idx + 1), size: 20 })] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: init.name, bold: true, size: 20 })] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: init.owner, size: 20 })] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: init.weightedScore.toFixed(2), size: 20 })] })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: tier, bold: true, size: 20 })] })] }),
                ]
              });
            })
          ]
        }),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Initiative-Prioritisation.docx");
}

// ─── TOOL 3: DECISION STACK ───────────────────────────────────────────────────
export async function exportDecisionStack({ title, names, scores, ws, winner, dims }) {
  const opts = ["a", "b", "c"];
  const winnerIdx = opts.indexOf(winner);

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("The Decision Stack"),
        labelValue("Decision", title),
        labelValue("Recommended Option", names[winnerIdx] || `Option ${winner.toUpperCase()}`),
        divider(),
        heading2("Score Summary"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["Dimension", "Weight", ...opts.map((o, i) => names[i] || `Option ${o.toUpperCase()}`)].map(h =>
                new TableCell({
                  shading: { type: ShadingType.SOLID, color: GREEN },
                  children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })]
                })
              )
            }),
            ...dims.map(dim => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: dim.label, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${Math.round(dim.weight * 100)}%`, size: 20 })] })] }),
                ...opts.map(opt => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(scores[opt][dim.id] || 0), size: 20 })] })] })),
              ]
            })),
            new TableRow({
              children: [
                new TableCell({ shading: { type: ShadingType.SOLID, color: "EEEEEE" }, children: [new Paragraph({ children: [new TextRun({ text: "WEIGHTED TOTAL", bold: true, size: 20 })] })] }),
                new TableCell({ shading: { type: ShadingType.SOLID, color: "EEEEEE" }, children: [new Paragraph({ text: "" })] }),
                ...opts.map(opt => new TableCell({
                  shading: { type: ShadingType.SOLID, color: opt === winner ? "D4F4E8" : "EEEEEE" },
                  children: [new Paragraph({ children: [new TextRun({ text: ws[opt].toFixed(2), bold: true, size: 22 })] })]
                })),
              ]
            }),
          ]
        }),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Decision-Stack.docx");
}

// ─── TOOL 4: ROLE ANALYSER ────────────────────────────────────────────────────
export async function exportRoleAnalyser({ form, result }) {
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1(form.role),
        labelValue("Organisation", form.org),
        form.level && labelValue("Level", form.level),
        form.reports && labelValue("Direct Reports", form.reports),
        divider(),
        heading2("Role Purpose"),
        body(result.rolePurpose),
        divider(),
        heading2("Top 3 Priorities"),
        ...result.top3Priorities.map((p, i) => new Paragraph({ children: [new TextRun({ text: `${i + 1}. ${p}`, size: 22 })], spacing: { after: 100 } })),
        divider(),
        heading2("What Success Looks Like"),
        body(result.whatSuccessLooksLike),
        labelValue("Top Focus Area", result.topFocusArea),
        labelValue("Biggest Risk", result.biggestRisk),
        divider(),
        heading2("Core Accountabilities"),
        ...result.coreAccountabilities.flatMap(acc => [
          new Paragraph({ children: [new TextRun({ text: acc.title, bold: true, size: 22, color: GREEN })], spacing: { before: 200, after: 80 } }),
          body(acc.description),
          ...acc.tasks.map(t => bullet(t)),
        ]),
        divider(),
        heading2("Decision Rights"),
        ...["own", "influence", "contribute", "escalate"].flatMap(type => [
          new Paragraph({ children: [new TextRun({ text: type.charAt(0).toUpperCase() + type.slice(1), bold: true, size: 22 })], spacing: { before: 160, after: 60 } }),
          ...result.decisionRights[type].map(d => bullet(d)),
        ]),
        divider(),
        heading2("KPIs"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["KPI", "What Good Looks Like", "How Measured"].map(h =>
                new TableCell({ shading: { type: ShadingType.SOLID, color: GREEN }, children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })] })
              )
            }),
            ...result.kpis.map(kpi => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.kpi, bold: true, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.goodLooksLike, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.measurement, size: 20 })] })] }),
              ]
            }))
          ]
        }),
        divider(),
        heading2("12-Month Roadmap"),
        ...result.roadmap.flatMap(r => [
          new Paragraph({ children: [new TextRun({ text: r.period, bold: true, size: 22, color: GREEN })], spacing: { before: 200, after: 80 } }),
          body(r.focus),
          bullet(`Milestone: ${r.milestone}`),
        ]),
        divider(),
        heading2("Risks"),
        ...result.risks.flatMap(r => [
          new Paragraph({ children: [new TextRun({ text: r.risk, bold: true, size: 22, color: "B94040" })], spacing: { before: 200, after: 60 } }),
          labelValue("Impact", r.impact),
          labelValue("Action", r.action),
        ]),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ].filter(Boolean)
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `SMR-Role-${form.role.replace(/\s+/g, '-')}.docx`);
}

// ─── TOOL 5: OPERATING RHYTHM ─────────────────────────────────────────────────
export async function exportRhythm({ orgName, meetings }) {
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("Operating Rhythm Register"),
        orgName && labelValue("Organisation / Programme", orgName),
        labelValue("Total Meetings", String(meetings.length)),
        divider(),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["Meeting", "Cadence", "Duration", "Purpose", "Owner"].map(h =>
                new TableCell({ shading: { type: ShadingType.SOLID, color: GREEN }, children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })] })
              )
            }),
            ...meetings.map(m => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: m.label, bold: true, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: m.cadence, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: m.duration, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: m.purpose || "—", size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: m.owner || "—", size: 20 })] })] }),
              ]
            }))
          ]
        }),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ].filter(Boolean)
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Operating-Rhythm.docx");
}

// ─── TOOL 6: KPI BUILDER ──────────────────────────────────────────────────────
export async function exportKPIs({ kpis, pillars }) {
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("KPI & Performance Scorecard"),
        labelValue("Total KPIs", String(kpis.length)),
        labelValue("Lead Indicators", String(kpis.filter(k => k.lead).length)),
        labelValue("Lag Indicators", String(kpis.filter(k => !k.lead).length)),
        divider(),
        ...pillars.flatMap(pillar => {
          const pk = kpis.filter(k => k.pillar === pillar.id);
          if (!pk.length) return [];
          return [
            heading2(pillar.label),
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  tableHeader: true,
                  children: ["KPI", "Target", "Frequency", "Type", "Formula"].map(h =>
                    new TableCell({ shading: { type: ShadingType.SOLID, color: GREEN }, children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })] })
                  )
                }),
                ...pk.map(kpi => new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.name, bold: true, size: 20 })] })] }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.target, size: 20 })] })] }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.frequency, size: 20 })] })] }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.lead ? "Lead" : "Lag", size: 20 })] })] }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: kpi.formula, size: 18, color: "555555" })] })] }),
                  ]
                }))
              ]
            }),
            new Paragraph({ text: "", spacing: { after: 200 } }),
          ];
        }),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-KPI-Scorecard.docx");
}

// ─── TOOL 7: CAPABILITY MAPPER ────────────────────────────────────────────────
export async function exportCapability({ domains, scores, imp, notes }) {
  const assessed = domains.filter(d => scores[d.id] > 0);
  const capLabel = s => !s ? "Not assessed" : ["","Critical Gap","Significant Gap","Partial","Capable","Strong"][s];

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("Capability & Gap Map"),
        labelValue("Domains Assessed", String(assessed.length)),
        labelValue("Critical Gaps", String(domains.filter(d => scores[d.id] === 1).length)),
        labelValue("Strengths", String(domains.filter(d => scores[d.id] >= 4).length)),
        divider(),
        heading2("Capability Assessment"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["Domain", "Score", "Importance", "Status", "Notes"].map(h =>
                new TableCell({ shading: { type: ShadingType.SOLID, color: GREEN }, children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })] })
              )
            }),
            ...domains.map(d => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: d.label, bold: true, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: scores[d.id] ? `${scores[d.id]}/5` : "—", size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${imp[d.id] || 3}/5`, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: capLabel(scores[d.id]), size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: notes[d.id] || "—", size: 18, color: "555555" })] })] }),
              ]
            }))
          ]
        }),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Capability-Map.docx");
}

// ─── TOOL 8: CHANGE & ADOPTION ────────────────────────────────────────────────
export async function exportChange({ changeName, changeType, groups, scope, adkarScores, rfactors, adkar, resistance, resResp, interventions }) {
  const complete = adkar.every(e => adkarScores[e.id] > 0);
  const weakest = complete ? adkar.reduce((min, el) => !adkarScores[el.id] || adkarScores[el.id] < (adkarScores[min?.id] || 6) ? el : min, null) : null;

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ children: [new TextRun({ text: "STRATEGY MADE REAL", bold: true, size: 28, color: GREEN })], spacing: { after: 50 } }),
        heading1("Change & Adoption Plan"),
        labelValue("Change", changeName),
        labelValue("Type", changeType),
        groups && labelValue("Impacted Groups", groups),
        labelValue("Scale", `${scope}/5`),
        divider(),
        heading2("ADKAR Assessment"),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: ["Element", "Score", "Status"].map(h =>
                new TableCell({ shading: { type: ShadingType.SOLID, color: GREEN }, children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: WHITE, size: 20 })] })] })
              )
            }),
            ...adkar.map(el => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: el.label, bold: true, size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: adkarScores[el.id] ? `${adkarScores[el.id]}/5` : "Not scored", size: 20 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: el.id === weakest?.id ? "⚠ Barrier Point" : adkarScores[el.id] >= 4 ? "Strong" : "Needs attention", size: 20 })] })] }),
              ]
            }))
          ]
        }),
        divider(),
        heading2("Recommended Interventions"),
        ...adkar.filter(el => (adkarScores[el.id] || 0) < 4).flatMap(el => [
          new Paragraph({ children: [new TextRun({ text: el.label, bold: true, size: 22, color: GREEN })], spacing: { before: 200, after: 80 } }),
          ...interventions[el.id].slice(0, adkarScores[el.id] === 1 ? 5 : adkarScores[el.id] === 2 ? 4 : 3).map(a => bullet(a)),
        ]),
        ...(rfactors.length > 0 ? [
          divider(),
          heading2("Resistance Response Plan"),
          ...rfactors.flatMap(id => {
            const factor = resistance.find(r => r.id === id);
            return [
              new Paragraph({ children: [new TextRun({ text: factor.label, bold: true, size: 22, color: "B94040" })], spacing: { before: 200, after: 80 } }),
              body(resResp[id]),
            ];
          })
        ] : []),
        divider(),
        body("Generated by Strategy Made Real — Strategy Execution Suite"),
      ].filter(Boolean)
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "SMR-Change-Adoption-Plan.docx");
}
